service: bus2
app: rutgersgraphql
org: ridhwaan

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: us-east-1

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get
